### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by mtvbrianking** [mtvbrianking/laravel-otp#1]
- [ ] Encrypt google2fa secret
- [ ] Test entire flow after session flush
- [ ] Write tests
- [ ] Update read me file
